[tool.poetry]
name = "gauss2d"
version = "0.1.0"
description = "Python (pybind11) bindings for gauss2d"
authors = ["taranu <dan.s.taranu@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
pybind11 = "^2.6.2"
numpy = "^1.20.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
